# Generated by Django 2.1.7 on 2019-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_thumbsup',
            field=models.IntegerField(default=0),
        ),
    ]
