# Generated by Django 2.1.7 on 2019-03-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_num_thumbsup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num_thumbsup',
            new_name='thumbsup',
        ),
    ]
