# Generated by Django 2.1.7 on 2019-03-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190318_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbsdown',
            field=models.IntegerField(default=0),
        ),
    ]
