# Generated by Django 2.1.7 on 2019-03-30 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190330_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputs', to=settings.AUTH_USER_MODEL),
        ),
    ]
