# Generated by Django 2.1.7 on 2019-03-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190330_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rep',
            field=models.IntegerField(default=10),
        ),
    ]
