# Generated by Django 2.1.7 on 2019-04-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190401_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
